translation to ES of review.md
ropensci/dev_guide pull request #303
Opened 2021-01-18 13:52 UTC by FvD

- Pull request to dev branch as per request of @maelle in #302

2021-01-18 13:58 UTC, maelle commented
:pray: muchas gracias

2021-01-18 13:59 UTC, maelle commented
I'll add the template to the book (via editing one Rmd) myself once the review has been approved by one native speaker. Thanks a ton again!

2021-01-20 02:16 UTC, maurolepore requested changes
Thanks a lot @FvD! 

In addition to the changes I suggest here, I also suggest some changes to the English version (@maelle I mentioned you in a few places -- let me know if you want me to follow up with a PR). Also, I think both versions would benefit from wrapping at 80 characters -- that make it easier for a reviewer to see exactly what changed when someone fixes a typo.

2021-01-20 02:16 UTC, maurolepore commented on templates/review-es.md
> +- [ ] **Funcionalidad:** Todo afirmación de funcionalidad del software se confirma como existente.
> - [ ] **Funcionalidad:** [Todo]^1 afirmación de funcionalidad del software se confirma como existente.

Instead I suggest the feminine [Toda] (modifies the feminine "la afirmación").

2021-01-20 02:16 UTC, maurolepore commented on templates/review-es.md
> +- [ ] Si la o las persona(s) autora(s) lo considera(n) apropiado, yo estoy de acuerdo con que me reconozcan como revisor del paquete (el rol "rev') en la el archivo DESCRIPTION del paquete.
I think it's correct. 

An alternative might be:

- [ ] Si me lo ofrecieran, acepto el rol "rev" en la el archivo DESCRIPTION del paquete.

2021-01-25 12:18 UTC, maelle commented on templates/review-es.md
> +**Por favor describe cualquier relación de trabajo que tienes/has tenido con los autores del paquete)**
Well we have two editors from Argentina so fine to use this form IMHO. :grin:

2021-01-25 12:21 UTC, maelle commented on templates/review-es.md
> +- [ ] **Documentación de las funciones** en la ayuda de R para todas la funciones exportadas
makes sense!

2021-01-25 12:23 UTC, merged

2021-01-25 12:23 UTC, maelle commented
Thanks @FvD & @maurolepore!

2021-01-25 12:26 UTC, maelle commented
(changes made in the English version too)