Update git workflow resources
ropensci/dev_guide pull request #374
Opened 2022-01-11 14:36 UTC by maelle

Fix #372

Thanks @statnmap @ha0ye for links to resources.

2022-01-11 19:19 UTC, mpadge requested changes

2022-01-11 19:19 UTC, mpadge commented on maintenance_collaboration.Rmd
> +You might want to pair the frequent updating with frequent version numbers incrementing (in `DESCRIPTION`).
"frequent version numbers increasing" -> "frequent version number incrementing" (singular) OR "frequent incrementing of version numbers" (correct English)

2022-01-11 19:19 UTC, mpadge commented on maintenance_collaboration.Rmd
> +Some useful guidance:
That dot-point should maybe be joined on to the prior one: "reviewing pull requests, with some useful guidance at:" (or something like that)

2022-01-13 10:57 UTC, mpadge approved these changes
ah, that's better. Nice!

2022-01-13 11:09 UTC, merged

2022-01-13 11:09 UTC, maelle commented
Thank you @mpadge