update CITATION instructions: 'citEntry' -> 'bibentry'; fixes #604
ropensci/dev_guide pull request #609
Opened 2023-02-09 12:50 UTC by mpadge

2023-02-09 12:53 UTC, maelle requested changes
I added two questions + the Spanish version is missing.

Thanks a ton!!

2023-02-09 12:54 UTC, mpadge commented on pkg_building.Rmd
> -As an example see [nasapower CITATION file](https://github.com/ropensci/nasapower/blob/master/inst/CITATION) that refers to both the manual and a paper.
Adam just asked about that on slack, so he's aware. I'm going to PR to dynamite to tweak a couple of things, and let them know that they're the benchmark :smile:

2023-02-09 12:55 UTC, mpadge commented on pkg_building.Rmd
Yes, but all of this stuff suggests as first action `usethis::use_citation`, and that's currently wrong :scream: . so we first have to wait for that to be fixed.

2023-02-09 13:22 UTC, maelle commented on pkg_building.Rmd
https://github.com/ropensci/roweb3/issues/484

2023-02-14 10:48 UTC, yabellini reviewed
Minor changes.

2023-02-14 10:48 UTC, yabellini commented on pkg_building.es.Rmd
> +- CRAN exige que los archivos CITATION se declaren como [`bibentry` items](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/bibentry.html) y no en la forma previamente aceptada de [`citEntry(
```suggestion
- CRAN exige que los archivos CITATION se declaren como [`bibentry` items](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/bibentry.html) y no en la forma aceptada previamente de [`citEntry()`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/citEntry.html).
```

2023-02-14 10:48 UTC, yabellini commented on pkg_building.es.Rmd
> +Como ejemplo, revisa el [archivo CITATION de dynamite](https://github.com/ropensci/dynamite/blob/main/inst/CITATION) se refiere al manual R, así como a otras publicaciones asociadas.
```suggestion
Como ejemplo, revisa el [archivo CITATION de dynamite](https://github.com/ropensci/dynamite/blob/main/inst/CITATION) donde se refiere al manual, así como a otras publicaciones asociadas.
```

2023-02-14 11:00 UTC, yabellini approved these changes

2023-02-14 11:28 UTC, merged