Uses parallel construction in the COI section
ropensci/dev_guide pull request #659
Opened 2023-04-21 19:45 UTC by eliocamp

This small PR changes the wording in the COI section so that every bulletpoint follows the same parallel construction.

2023-04-24 07:39 UTC, mpadge requested changes
Thanks @eliocamp. Please ping again once you've accepted those minor suggestions (with modification if you like), and we'll happily approve.

2023-04-24 07:39 UTC, mpadge commented on softwarereview_policies.Rmd
> +* The potential reviewer/editor are from the institution or institutional component (e.g., department) of any author with a major role.
```suggestion
* The potential reviewer/editor are from the same institution or institutional component (e.g., department) as any author with a major role. 
```

2023-04-24 07:39 UTC, mpadge commented on softwarereview_policies.Rmd
> +* The potential reviewer/editor has been a collaborator or has had any other professional relationship with any person on the package who has a major role within in the past three year.
```suggestion
* The potential reviewer/editor has been a collaborator or has had other professional relationships with at least one person on the package who has a major role within in the past three year.
```

2023-04-24 07:39 UTC, mpadge commented on softwarereview_policies.Rmd
> +* The potential reviewer/editor would receive a direct or indirect financial benefit if the package is accepted.
```suggestion
* The potential reviewer/editor would receive a direct or indirect financial benefit if the package were accepted.
```

2023-04-24 07:39 UTC, mpadge commented on softwarereview_policies.Rmd
> +* The potential reviewer/editor serves as a member of the advisory board for the project under review.
```suggestion
* The potential reviewer/editor serves, or has served, as a member of the advisory board for the project under review.
```

2023-04-24 17:38 UTC, eliocamp commented
@mpadge There you go, all accepted. :)

2023-04-25 07:38 UTC, mpadge commented
One more request @eliocamp: could you please add a line desribing these changes to the [changelog](https://github.com/ropensci/dev_guide/blob/main/booknews.Rmd) as well? Let us know, and then I'll approve and merge. Thanks

2023-04-25 17:02 UTC, eliocamp commented
Ready! Let me know if it looks good.

2023-04-26 07:44 UTC, mpadge approved these changes
Great, thanks!

2023-04-26 07:45 UTC, merged