First Review redirect.pt.Rmd
ropensci/dev_guide pull request #788
Opened 2024-01-05 22:35 UTC by IldySilva

the #777

2024-01-08 19:52 UTC, yabellini commented
This is great @IldySilva !  Thank you :-) Can you email me at yabellini@ropensci.org so I can send the Slack invitation?

2024-01-13 13:38 UTC, pedropark99 requested changes

2024-01-13 13:38 UTC, pedropark99 commented on redirect.pt.Rmd
> +Substitua o conteúdo do site atual por um arquivos com o nome `index.html` e um com nome  `404.html` contendo ambos os arquivos:
```suggestion
Substitua o conteúdo do site atual por dois arquivos chamados `index.html` e `404.html`. Ambos os arquivos devem conter o seguinte conteúdo:
```

2024-01-13 13:38 UTC, pedropark99 commented on redirect.pt.Rmd
> +Substitua o conteúdo do site atual por um arquivos com o nome `index.html` e um com nome  `404.html` contendo ambos os arquivos:
This makes the intent of the phrase more clear

2024-01-13 14:50 UTC, pedropark99 commented
@yabellini  this PR is ready to be merged since both reviews are done 😉

2024-01-14 14:37 UTC, merged