Add PT-BR automatic translation pkg_security.pt.Rmd
ropensci/dev_guide pull request #823
Opened 2024-03-13 16:39 UTC by yabellini

2024-11-26 17:52 UTC, yabellini commented
Great @arianacabral, thank you!

2024-12-20 20:52 UTC, arianacabral requested changes
I completed the first review, @yabellini.

I hope that soon we can finish reviewing this chapter as well 😊

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +Isso obviamente significa que as verificações de PR pelo CI não são exaustivas, portanto, você precisará verificar o PR localmente para executar todos os testes.
```suggestion
 Isso significa, portanto, que as verificações de PR feitas pela CI não serão exaustivas e, como consequência, você precisará verificar o PR localmente para executar todos os testes.
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +Documente o comportamento do seu pacote para PRs externos em [CONTRIBUTING.md](#friendlyfiles) para o bem das pessoas que fazem PRs e das pessoas que as revisam (você em algumas semanas e outros auto
```suggestion
Documente o comportamento do seu pacote em relação a PRs externos no arquivo [CONTRIBUTING.md](#friendlyfiles). Isso será útil tanto para quem faz PRs quanto para quem os revisa, seja você no futuro ou outros mantenedores do pacote.
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +### Segredos e CRAN {#secrets-and-cran}
```suggestion
### Credenciais e CRAN {#secrets-and-cran}
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +No CRAN, ignore todos os testes (`skip_on_cran()`) e exemplos (`dontrun`) que exijam credenciais.
```suggestion
No CRAN, ignore quaisquer testes (`skip_on_cran()`) e exemplos (`dontrun`) que exijam credenciais.
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +[Vinhetas de pré-computação](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/) que requerem credenciais.
```suggestion
[Gere previamente as vignettes](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/) que requerem credenciais.
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +Recursos úteis de segurança:
```suggestion
Materiais úteis sobre segurança:
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +- [Chamada da comunidade rOpenSci "Segurança para R"](https://ropensci.org/commcalls/2019-05-07/) (gravação, slides, etc. veja em particular [a lista de recursos](https://ropensci.org/blog/2019/04/09
```suggestion
- [a sessão da comunidade rOpenSci "Segurança para R"](https://ropensci.org/commcalls/2019-05-07/) (veja a gravação, slides, etc. e, em particular, [a lista de recursos](https://ropensci.org/blog/2019/04/09/commcall-may2019/#resources));
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +- [os projetos relacionados à segurança da unconf18](https://ropensci.org/blog/2018/06/06/unconf18_recap_2/);
```suggestion
- [os projetos relacionados à segurança do unconf18](https://ropensci.org/blog/2018/06/06/unconf18_recap_2/);
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +- [`gargle` artigo "Gerenciando tokens de forma segura"](gargle.r-lib.org/articles/articles/managing-tokens-securely.html)
```suggestion
- [artigo do pacote `gargle` "Gerenciando tokens de forma segura"](gargle.r-lib.org/articles/articles/managing-tokens-securely.html)
```

2024-12-20 20:52 UTC, arianacabral commented on pkg_security.pt.Rmd
> +Digamos que seu pacote precise de uma chave de API para fazer solicitações em nome dos usuários do seu pacote.
```suggestion
Digamos que seu pacote precise de uma chave de API para fazer solicitações em nome dos(as) usuários(as) do seu pacote.
```

2024-12-20 21:20 UTC, yabellini reviewed
Removing YAML to avoid build errors

2024-12-20 21:20 UTC, yabellini commented on pkg_security.pt.Rmd
> +---
```suggestion

```

2024-12-20 21:20 UTC, yabellini commented on pkg_security.pt.Rmd
> +aliases: security.html
```suggestion

```

2024-12-20 21:20 UTC, yabellini commented on pkg_security.pt.Rmd
> +---
```suggestion

```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +Documente as etapas que você fez em [CONTRIBUINDO.md](#friendlyfiles) para que você, ou um novo mantenedor, possa se lembrar como proceder da próxima vez.
```suggestion
Documente as etapas em [CONTRIBUINDO.md](#friendlyfiles) para que você, ou um(a) novo(a) mantenedor(a), possa se lembrar como proceder da próxima vez.
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +E quanto a pull requests de colaboradores externos?
```suggestion
E quanto a pull requests de colaboradores(as) externos(as)?
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +No GitHub, por exemplo, as credenciais só estão disponíveis para GitHub Actions em pull requests iniciados a partir do próprio repositório, e não a partir de um fork.
```suggestion
No GitHub, por exemplo, as credenciais só estão disponíveis para o GitHub Actions em pull requests iniciados a partir do próprio repositório, e não a partir de um fork.
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +Os testes que usam suas credenciais falharão, a menos que você use algum tipo de resposta simulada ou em cache, portanto, pode ser interessante ignorá-los dependendo do contexto.
```suggestion
Os testes que usam as suas credenciais falharão, ao menos que você use algum tipo de resposta simulada ou em cache, portanto, pode ser interessante ignorá-los dependendo do contexto.
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +Documente o comportamento do seu pacote em relação a PRs externos no arquivo [CONTRIBUTING.md](#friendlyfiles). Isso será útil tanto para quem faz PRs quanto para quem os revisa, seja você no futuro
```suggestion
Documente o comportamento do seu pacote em relação a PRs externos no arquivo [CONTRIBUTING.md](#friendlyfiles). Isso será útil tanto para quem faz PRs quanto para quem os revisa, seja você no futuro ou outras pessoas mantenedoras do pacote.
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +[Gere previamente as vignettes](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/) que requerem credenciais.
```suggestion
[Gere previamente as vinhetas](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/) que requerem credenciais.
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +- [a sessão da comunidade rOpenSci "Segurança para R"](https://ropensci.org/commcalls/2019-05-07/) (veja a gravação, slides, etc. e, em particular, [a lista de recursos](https://ropensci.org/blog/201
```suggestion
- [a sessão da comunidade rOpenSci "Segurança para R"](https://ropensci.org/commcalls/2019-05-07/) (veja a gravação, os slides, etc. e, em particular, [a lista de recursos](https://ropensci.org/blog/2019/04/09/commcall-may2019/#resources));
```

2025-04-17 03:29 UTC, fblpalmeira commented on pkg_security.pt.Rmd
> +- [artigo do pacote `gargle` "Gerenciando tokens de forma segura"](gargle.r-lib.org/articles/articles/managing-tokens-securely.html)
```suggestion
- [o artigo do pacote `gargle` "Gerenciando tokens de forma segura"](gargle.r-lib.org/articles/articles/managing-tokens-securely.html)
```

2025-04-17 03:46 UTC, fblpalmeira commented
@yabellini I completed the second review of the chapter (#823). Let me know if I missed anything.

2025-04-17 14:03 UTC, merged