Add review for Portuguese translation of `softwarereview_reviewer.pt.Rmd`
ropensci/dev_guide pull request #851
Opened 2024-11-18 14:08 UTC by pedropark99

This PR is adding the first review of `softwarereview_reviewer.pt.Rmd`.

2024-11-26 17:34 UTC, arianacabral commented
I can conduct the second review of this chapter.

2024-11-26 17:46 UTC, pedropark99 commented
Hey @arianacabral ! Thank you very much for your interest! If you want to, you can perform this second review by simply reviewing the changes in this PR 😉.

You review the changes by going into the "Files changed" panel in this PR. In other words, go to this link and review the changes: https://github.com/ropensci/dev_guide/pull/851/files

2024-11-27 10:10 UTC, arianacabral commented
> Hey @arianacabral ! Thank you very much for your interest! If you want to, you can perform this second review by simply reviewing the changes in this PR 😉.
> 
> You review the changes by going into the "Files changed" panel in this PR. In other words, go to this link and review the changes: https://github.com/ropensci/dev_guide/pull/851/files

Hi, @pedropark99! 

Thank you for providing the details! 

I’ll review the changes in the "Files changed" panel and will share my feedback as soon as possible 😊

2024-11-29 18:32 UTC, arianacabral requested changes
Hi, @pedropark99!

I have completed the second review.

I must say that I was very impressed with the first review; it was very good.

In this second review, I made just a few minor adjustments to improve some sentences and to standardize the reference to certain terms. However, please feel free to modify any of my suggestions if you think it’s necessary. 

For some points where I had doubts, I’ve left comments.

2024-11-29 18:32 UTC, arianacabral commented on softwarereview_reviewer.pt.Rmd
>  - `rtika` [revisão 1](https://github.com/ropensci/software-review/issues/191#issuecomment-367166658) e [revisão2](https://github.com/ropensci/software-review/issues/191#issuecomment-368254623)
Acredito que talvez faça mais sentido, para quem está lendo, manter essa estrutura. Se achar adequado, pode alterar as demais para que fiquem todos os exemplos no mesmo padrão.

```suggestion
- [revisão 1](https://github.com/ropensci/software-review/issues/191#issuecomment-367166658) e [revisão2](https://github.com/ropensci/software-review/issues/191#issuecomment-368254623) de `rtika`
```

2024-12-13 23:56 UTC, pedropark99 commented on softwarereview_reviewer.pt.Rmd
> +Tente ao máximo concluir sua avaliação em até 3 semanas após o aceite da solicitação de avaliação. Nós vamos lembrar os revisores das datas de vencimento, tanto futuras quanto passadas. Os(as) editor
I just noticed the lack of "(as)" in this other instance.

```suggestion
Tente ao máximo concluir sua avaliação em até 3 semanas após o aceite da solicitação de avaliação. Nós vamos lembrar os(as) revisores(as) das datas de vencimento, tanto futuras quanto passadas. Os(as) editores(as) podem designar revisores(as) adicionais ou alternativos se uma revisão estiver muito atrasada.
```

2024-12-14 00:00 UTC, pedropark99 commented on softwarereview_reviewer.pt.Rmd
> +Se você ver um envio atual que seja particularmente relevante para os seus interesses, envie um e-mail para `info@ropensci.org` incluindo o nome do pacote, a URL do *issue* que corresponde a este env
O termo "issue" está sendo mantido intacto. Pois a tradução direta "problema" é muito esquisita, e não ajuda muito a entendermos o significado original (isto é, uma issue do GitHub).

2024-12-14 00:08 UTC, pedropark99 commented on softwarereview_reviewer.pt.Rmd
> +Todos os envios criam um relatório detalhado sobre a estrutura e a funcionalidade do pacote enviado. Tal relatório é gerado pelo nosso pacote [`pkgcheck`](https://docs.ropensci.org/pkgcheck/). Se o p
Boa! Excelente essa mudança

2024-12-14 00:15 UTC, pedropark99 commented on softwarereview_reviewer.pt.Rmd
>  - `rtika` [revisão 1](https://github.com/ropensci/software-review/issues/191#issuecomment-367166658) e [revisão2](https://github.com/ropensci/software-review/issues/191#issuecomment-368254623)
Faz sentido mesmo mudar essa estrutura dessa forma.

2024-12-14 00:17 UTC, pedropark99 commented
First of all, thank you very much @arianacabral for your review!

@yabellini  the two reviews are done, we can proceed with this PR.

2024-12-14 23:59 UTC, merged